### ISSUE TITLE
NoMethodError: undefined method `snakeize_keys' for #<ActiveSupport::OrderedHash:0x007f8ef22d3970>

### ISSUE THREAD

**Issue by anarchivist** [IIIF/osullivan#48]
On `osullivan` 0.0.3, Ruby 2.1.5 - I'm working with [Shimmy](https://github.com/mejackreed/shimmy) to build a manifest on my personal computer (not the one I brought to the hackathon).

```ruby
[5] pry(main)> m = Shimmy::Shims::FlickrSet.new(set_id: '72157659051355812')
=> #<Shimmy::Shims::FlickrSet:0x007f8ef3239e00
[6] pry(main)> m.update_blob
NoMethodError: undefined method `snakeize_keys' for #<ActiveSupport::OrderedHash:0x007f8ef22d3970>
from /Users/mark/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/osullivan-0.0.3/lib/iiif/service.rb:27:in `initialize'
```

Explicitly requiring `lib/active_support/ordered_hash.rb` fixes it, as expected.

**Comment by jpstroop** [comment]
PR? :wink:

**Comment by anarchivist** [comment]
Well, I'd be happy to submit a PR if I knew the best way to fix it! :) The weird thing is that I *didn't* run into this problem at the hackathon (also using `osullivan` 0.0.3, but on Ruby 2.1.3).

**Comment by jpstroop** [comment]
Ah, I see now. I'll try to look into it later this week. Thanks for the extra info.

**Comment by anarchivist** [comment]
Also, FWIW, I forked `osullivan` to test it on some more versions of Ruby, but the all the tests passed.

**Comment by jcoyne** [comment]
Any update on this?  I'm seeing it here: https://travis-ci.org/projecthydra-labs/hybox/builds/126559939

**Comment by ruthtillman** [comment]
Running into same issue today, 2.3.1. 

```
/Users/rtillman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/osullivan-0.0.3/lib/iiif/service.rb:27:in `initialize': undefined method `snakeize_keys' for #<ActiveSupport::OrderedHash:0x007fbef31cb010> (NoMethodError)
	from /Users/rtillman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/osullivan-0.0.3/lib/iiif/presentation/abstract_resource.rb:53:in `initialize'
	from /Users/rtillman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/osullivan-0.0.3/lib/iiif/presentation/manifest.rb:27:in `initialize'
	from processor.rb:14:in `new'
	from processor.rb:14:in `<main>'
```

**Comment by anarchivist** [comment]
@ruthtillman I think you might want to run `gem uninstall osullivan` and then `gem install iiif-presentation`.

**Comment by ruthtillman** [comment]
There it is! Thank you so much, @anarchivist ^_^
